from app.models import ToolDefinition, ToolField


TOOL_DEFINITIONS = [
    ToolDefinition(
        key="pcd_map",
        title="pcd -> pgm",
        subtitle="PCD 生成 SLAM 地图",
        description="已接 C++ pcd_map_cli，当前可从 Web 界面触发真实地图生成。",
        primary_action="Generate Map",
        secondary_action="Browse",
        fields=[
            ToolField(key="input_pcd", label="Input PCD", placeholder="G:/path/map.pcd"),
            ToolField(key="output_dir", label="Output Dir", value="G:/ros_proj/ros_tool/output"),
            ToolField(key="base_name", label="Base Name", value="map"),
            ToolField(key="resolution", label="Resolution", value="0.05"),
            ToolField(key="clip_min_z", label="Clip Min Z", value="-1.0"),
            ToolField(key="clip_max_z", label="Clip Max Z", value="2.0"),
            ToolField(key="walkable_min_z", label="Walkable Min Z", value="-0.2"),
            ToolField(key="walkable_max_z", label="Walkable Max Z", value="0.2"),
            ToolField(key="obstacle_min_z", label="Obstacle Min Z", value="0.25"),
            ToolField(key="obstacle_max_z", label="Obstacle Max Z", value="2.0"),
            ToolField(key="ground_tolerance", label="Ground Tolerance", value="0.12"),
            ToolField(key="min_points_per_cell", label="Min Points / Cell", value="1"),
            ToolField(key="obstacle_inflate_radius", label="Inflate Radius", value="0.1"),
            ToolField(key="hole_fill_neighbors", label="Hole Fill Neighbors", value="5"),
            ToolField(key="overlay_smooth_radius", label="Overlay Smooth Radius", value="0.0"),
        ],
    ),
    ToolDefinition(
        key="pcd_tile",
        title="pcd slicing",
        subtitle="点云切片与 metadata",
        description="后续接 C++ pcd_tile_cli，当前先提供统一交互层。",
        primary_action="Split Tiles",
        secondary_action="Browse",
        fields=[
            ToolField(key="input_pcd", label="Input PCD", placeholder="G:/path/map.pcd"),
            ToolField(key="output_dir", label="Output Dir", value="G:/ros_proj/ros_tool/output_tiles"),
            ToolField(key="tile_size", label="Tile Size", value="20.0"),
            ToolField(key="overlap", label="Overlap", value="0.0"),
            ToolField(key="format", label="Format", value="binary"),
            ToolField(key="zip_output", label="Zip Output", value="false"),
        ],
    ),
    ToolDefinition(
        key="network_scan",
        title="ip check",
        subtitle="局域网扫描",
        description="后续接 C++ network_scan_cli 或 Python 服务层。",
        primary_action="Scan Network",
        secondary_action="Export",
        fields=[
            ToolField(key="prefix", label="Prefix", value="192.168.1"),
            ToolField(key="start", label="Start", value="1"),
            ToolField(key="end", label="End", value="32"),
            ToolField(key="timeout_ms", label="Timeout", value="400"),
            ToolField(key="filter", label="Filter", value=""),
            ToolField(key="threads", label="Threads", value="64"),
        ],
    ),
    ToolDefinition(
        key="costmap",
        title="bag replay",
        subtitle="Costmap 回放",
        description="后续接 C++ costmap_cli，当前先打通前后端壳。",
        primary_action="Process Costmap",
        secondary_action="Browse",
        fields=[
            ToolField(key="yaml_path", label="Input YAML", placeholder="G:/path/costmap.yaml"),
            ToolField(key="output_dir", label="Output Dir", value="G:/ros_proj/ros_tool/output_costmap"),
            ToolField(key="fps", label="FPS", value="2.0"),
            ToolField(key="export_gif", label="Export GIF", value="true"),
            ToolField(key="threshold", label="Threshold", value="99"),
            ToolField(key="footprint", label="Footprint", value="0.70x0.40"),
        ],
    ),
]
